### ISSUE TITLE
Not works on Firefox browser

### ISSUE THREAD

**Issue by sbotirov** [toptal/gitignore.io#577]
### Development Environment:

- [ ] Machine (Local, Container, Virtual):
- [x] Operating System (Name/Version): MacOS 12.3.1
- [x] Web Browser (Name/Version): Firefox
- [ ] Vapor Version:
- [ ] Swift Version:

### Expected Behavior:
Generate gitignore file for swift ios projects

### Actual Behavior:
_Create_ button doesn't works when click to it

### Reproduction Steps:
Just open: [gitignore.io](https://www.toptal.com/developers/gitignore) web site and type Swift to input field then press to _create_ button

<img width="1631" alt="image" src="https://user-images.githubusercontent.com/87771625/163926198-6291a837-3c42-43af-8337-ef70561c17a0.png">

**Comment by Isitar** [comment]
https://github.com/toptal/gitignore.io/issues/576

only happens with add block

**Comment by PhoneixS** [comment]
It happens to me, this is the console output:

```
Solicitud de origen cruzado bloqueada: La misma política de origen no permite la lectura de recursos remotos en https://static.cloudflareinsights.com/beacon.min.js/v652eace1692a40cfa3763df669d7439c1639079717194. (Razón: Solicitud CORS sin éxito). Código de estado: (null).

Ninguno de los hashes "sha512" en el atributo integrity coinciden con el contenido del subrecurso. [gitignore](https://www.toptal.com/developers/gitignore)
Solicitud de origen cruzado bloqueada: La misma política de origen no permite la lectura de recursos remotos en https://static.cloudflareinsights.com/beacon.min.js/v652eace1692a40cfa3763df669d7439c1639079717194. (Razón: Solicitud CORS sin éxito). Código de estado: (null).

Ninguno de los hashes "sha512" en el atributo integrity coinciden con el contenido del subrecurso. gitignore
El recurso en “https://www.toptal.com/developers/[gitignore](https://www.toptal.com/developers/gitignore)/fonts/ProximaNova-Regular.woff” precargado con precarga de enlace no se usó en unos pocos segundos. Asegúrese de que todos los atributos de la etiqueta de preload estén configurados correctamente. gitignore
El recurso en “https://www.toptal.com/developers/gitignore/fonts/ProximaNova-Regular.woff2” precargado con precarga de enlace no se usó en unos pocos segundos. Asegúrese de que todos los atributos de la etiqueta de preload estén configurados correctamente. [gitignore](https://www.toptal.com/developers/gitignore)
El recurso en “https://www.toptal.com/developers/gitignore/fonts/ProximaNova-Regular.otf” precargado con precarga de enlace no se usó en unos pocos segundos. Asegúrese de que todos los atributos de la etiqueta de preload estén configurados correctamente. gitignore
El recurso en “https://www.toptal.com/developers/[gitignore](https://www.toptal.com/developers/gitignore)/fonts/ProximaNova-Semibold.woff” precargado con precarga de enlace no se usó en unos pocos segundos. Asegúrese de que todos los atributos de la etiqueta de preload estén configurados correctamente. gitignore
El recurso en “https://www.toptal.com/developers/[gitignore](https://www.toptal.com/developers/gitignore)/fonts/ProximaNova-Semibold.woff2” precargado con precarga de enlace no se usó en unos pocos segundos. Asegúrese de que todos los atributos de la etiqueta de preload estén configurados correctamente. gitignore
El recurso en “https://www.toptal.com/developers/[gitignore](https://www.toptal.com/developers/gitignore)/fonts/ProximaNova-Semibold.otf” precargado con precarga de enlace no se usó en unos pocos segundos. Asegúrese de que todos los atributos de la etiqueta de preload estén configurados correctamente. gitignore
```

It could be because of the wrong CORS configuration or is it an unrelated library?

**Comment by flleeppyy** [comment]
Tested on a fresh install of Firefox and Firefox developer edition and still same result.

**Comment by Yalchin403** [comment]
Happens to me too, any solutions?

**Comment by wlkr** [comment]
In the meantime I've found that you can use the API directly to workaround this, e.g. [https://www.toptal.com/developers/gitignore/api/Swift,macOS?format=lines](https://www.toptal.com/developers/gitignore/api/Swift,macOS?format=lines).

**Comment by mauvehed** [comment]
Same issue here. I have DNS adblock, browser adblock extensions, strict privacy controls, etc. I have no idea which one of these broke it, so I can't just fix it. For now I have to use Chrome which is odd since it also uses the similar DNS adblock, browser extensions, privacy controls, etc.

**Comment by PhoneixS** [comment]
I have just tried again in Firefox and it is running ok for me now.

**Comment by rungxanh1995** [comment]
I just checked, and it's working with Chrome and Firefox (no need to disable any add-ons), but not Safari 😂

**Comment by animalillo** [comment]
It's not working here with firefox 100.0 on linux, can pick the tags, but the generate button does nothing at all

**Comment by Th3Ph4nt0m** [comment]
I'm having the same problem with Brave ([Version 1.38.119 Chromium: 101.0.4951.67 (Official Build) (64-bit)](https://brave.com/latest/)) on Windows 10. However, it works for me in Firefox (Developer Edition).

**Comment by leonidpodriz** [comment]
Try to check for privacy extensions in your browser. I had the same problem, but everything works fine after disabling the "DuckDuckGo Privacy Essentials" extension.

**Comment by filipechagas** [comment]
Thanks for reporting!

We have added this issue to our backlog and should be releasing a fix soon.

Also relates to https://github.com/toptal/gitignore.io/issues/576

**Comment by filipechagas** [comment]
A fix has been released 🚀 
Please, let us know if you encounter any further issues.
Thanks again for the report!

**Comment by MarcusOtter** [comment]
I'm also just running uBlock Origin. Cache is clear, still no go. The only difference I can tell from your setup is that I'm on Windows, and I'm on a VPN but no Pi-hole like ad-blocking. The only network requests that are blocked by uBlock are the ones to `static.cloudflareinsights.com` which I assume is okay.

Console has this error twice, but otherwise only warnings (except for the uBlock requests previously mentioned):
```
None of the "sha512" hashes in the integrity attribute match the content of the subresource.
```

**Comment by RajrupDasid** [comment]
Umm , issue still exists , even with no ad block
